---
name: "build"
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "mainline"
  pull_request:
    branches:
      - "mainline"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - name: "build containers"
        run: "make containers"
